# ansible n2 -m copy -a "src=maintenance.html dest=/var/www/html/index.html" 
---
- name: static page
  hosts: g1
  become: yes

  tasks:
  - name: update dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html


...
